 
 export const allBanks : {[key: string]: string[]} ={
    'Nigeria': [
    "Access Bank",
    "Citibank",
    "Diamond Bank",
    "Dynamic Standard Bank",
    "Ecobank Nigeria",
    "Fidelity Bank Nigeria",
    "First Bank of Nigeria",
    "First City Monument Bank",
    "Guaranty Trust Bank",
    "Heritage Bank Plc",
    "Jaiz Bank",
    "Keystone Bank Limited",
    "Providus Bank Plc",
    "Polaris Bank",
    "Stanbic IBTC Bank Nigeria Limited",
    "Standard Chartered Bank",
    "Sterling Bank",
    "Suntrust Bank Nigeria Limited",
    "Union Bank of Nigeria",
    "United Bank for Africa",
    "Unity Bank Plc",
    "Wema Bank",
    "Zenith Bank",
],
'Unitedstatesofamerica': [
    "Bank of America",
    'Wells Fargo Bank,',
    'Citi Bank',
    'JP Morgan Chase Bank',
    'Bank of the West',
    'U.S Bank',
    'CIT Bank',
    'MUFG Union Bank',
    'Comerica Bank',
    'Rabobank',
    'Umpqua Bank',
    'Banc of California',
    'HSBC',
    'City National Bank',
    'Westamerica Bank',
    'First Bank',
    'Pacific Premier Bank',
    'Compass Bank',
    'Pacific Western Bank',
    'Banner Bank',
    'Opus Bank	Opus Bank',
    'Mechanics Bank',
    'Citizens Business Bank',
    'Tri Counties Bank',
    'Cathay Bank',
    'Bank of Hope',
    'Bank of the Sierra',
    'Homestreet Bank',
    'Community Bank',
    'Fremont Bank',
    'United Business Bank',
    'Bank of Stockton',
    'Exchange Bank',
    'Heritage Bank of Commerce',
    'Grandpoint Bank',
    'Hanmi Bank',
    'Bank of Marin',
    'Royal Business Bank',
    'River City Bank',
    'Poppy Bank',
    'Manufacturers Bank',
    'United Security Bank',
    'Bank of England',
    'Scott Valley Bank',
    'Open Bank',
    'Ever Trust Bank',
    'Mission Bank',
    'Beneficial State Bank',
    'Community West Bank',
    'Armed Forces Bank',
    'CTBC Bank Corp',
],
'UnitedStatesofAmerica': [
    "Bank of America",
    'Wells Fargo Bank,',
    'Citi Bank',
    'JP Morgan Chase Bank',
    'Bank of the West',
    'U.S Bank',
    'CIT Bank',
    'MUFG Union Bank',
    'Comerica Bank',
    'Rabobank',
    'Umpqua Bank',
    'Banc of California',
    'HSBC',
    'City National Bank',
    'Westamerica Bank',
    'First Bank',
    'Pacific Premier Bank',
    'Compass Bank',
    'Pacific Western Bank',
    'Banner Bank',
    'Opus Bank	Opus Bank',
    'Mechanics Bank',
    'Citizens Business Bank',
    'Tri Counties Bank',
    'Cathay Bank',
    'Bank of Hope',
    'Bank of the Sierra',
    'Homestreet Bank',
    'Community Bank',
    'Fremont Bank',
    'United Business Bank',
    'Bank of Stockton',
    'Exchange Bank',
    'Heritage Bank of Commerce',
    'Grandpoint Bank',
    'Hanmi Bank',
    'Bank of Marin',
    'Royal Business Bank',
    'River City Bank',
    'Poppy Bank',
    'Manufacturers Bank',
    'United Security Bank',
    'Bank of England',
    'Scott Valley Bank',
    'Open Bank',
    'Ever Trust Bank',
    'Mission Bank',
    'Beneficial State Bank',
    'Community West Bank',
    'Armed Forces Bank',
    'CTBC Bank Corp',
],

'India': [
'ABHYUDAYA CO-OP BANK LTD',
'ABU DHABI COMMERCIAL BANK',
'AKOLA DISTRICT CENTRAL CO-OPERATIVE BANK',
'AKOLA JANATA COMMERCIAL COOPERATIVE BANK',
'ALLAHABAD BANK',
'ALMORA URBAN CO-OPERATIVE BANK LTD.',
'ANDHRA BANK',
'ANDHRA PRAGATHI GRAMEENA BANK',
'APNA SAHAKARI BANK LTD',
'AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED.',
'AXIS BANK',
'BANK INTERNASIONAL INDONESIA',
'BANK OF AMERICA',
'BANK OF BAHRAIN AND KUWAIT',
'BANK OF BARODA',
'BANK OF CEYLON',
'BANK OF INDIA',
'BANK OF MAHARASHTRA',
'BANK OF TOKYO-MITSUBISHI UFJ LTD.',
'BARCLAYS BANK PLC',
'BASSEIN CATHOLIC CO-OP BANK LTD',
'BHARATIYA MAHILA BANK LIMITED',
'BNP PARIBAS',
'CALYON BANK',
'CANARA BANK',
'CAPITAL LOCAL AREA BANK LTD.',
'CATHOLIC SYRIAN BANK LTD.',
'CENTRAL BANK OF INDIA',
'CHINATRUST COMMERCIAL BANK',
'CITIBANK NA',
'CITIZENCREDIT CO-OPERATIVE BANK LTD',
'CITY UNION BANK LTD',
'COMMONWEALTH BANK OF AUSTRALIA',
'CORPORATION BANK',
'CREDIT SUISSE AG',
'DBS BANK LTD',
'DENA BANK',
'DEUTSCHE BANK',
'DEUTSCHE SECURITIES INDIA PRIVATE LIMITED',
'DEVELOPMENT CREDIT BANK LIMITED',
'DHANLAXMI BANK LTD',
'DICGC',
'DOMBIVLI NAGARI SAHAKARI BANK LIMITED',
'FIRSTRAND BANK LIMITED',
'GOPINATH PATIL PARSIK JANATA SAHAKARI BANK LTD',
'GURGAON GRAMIN BANK',
'HDFC BANK LTD',
'HSBC',
'ICICI BANK LTD',
'IDBI BANK LTD',
'IDRBT',
'INDIAN BANK',
'INDIAN OVERSEAS BANK',
'INDUSIND BANK LTD',
'INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED',
'ING VYSYA BANK LTD',
'JALGAON JANATA SAHKARI BANK LTD',
'JANAKALYAN SAHAKARI BANK LTD',
'JANASEVA SAHAKARI BANK (BORIVLI) LTD',
'JANASEVA SAHAKARI BANK LTD. PUNE',
'JANATA SAHAKARI BANK LTD (PUNE)',
'JPMORGAN CHASE BANK N.A',
'KALLAPPANNA AWADE ICH JANATA S BANK',
'KAPOL CO OP BANK',
'KARNATAKA BANK LTD',
'KARNATAKA VIKAS GRAMEENA BANK',
'KARUR VYSYA BANK',
'KOTAK MAHINDRA BANK',
'KURMANCHAL NAGAR SAHKARI BANK LTD',
'MAHANAGAR CO-OP BANK LTD',
'MAHARASHTRA STATE CO OPERATIVE BANK',
'MASHREQBANK PSC',
'MIZUHO CORPORATE BANK LTD',
'MUMBAI DISTRICT CENTRAL CO-OP. BANK LTD.',
'NAGPUR NAGRIK SAHAKARI BANK LTD',
'NATIONAL AUSTRALIA BANK',
'NEW INDIA CO-OPERATIVE BANK LTD.',
'NKGSB CO-OP BANK LTD',
'NORTH MALABAR GRAMIN BANK',
'NUTAN NAGARIK SAHAKARI BANK LTD',
'OMAN INTERNATIONAL BANK SAOG',
'ORIENTAL BANK OF COMMERCE',
'PARSIK JANATA SAHAKARI BANK LTD',
'PRATHAMA BANK',
'PRIME CO OPERATIVE BANK LTD',
'PUNJAB AND MAHARASHTRA CO-OP BANK LTD.',
'PUNJAB AND SIND BANK',
'PUNJAB NATIONAL BANK',
'RABOBANK INTERNATIONAL (CCRB)',
'RAJGURUNAGAR SAHAKARI BANK LTD.',
'RAJKOT NAGARIK SAHAKARI BANK LTD',
'RESERVE BANK OF INDIA',
'SBERBANK',
'SHINHAN BANK',
'SHRI CHHATRAPATI RAJARSHI SHAHU URBAN CO-OP BANK LTD',
'SOCIETE GENERALE',
'SOLAPUR JANATA SAHKARI BANK LTD.SOLAPUR',
'SOUTH INDIAN BANK',
'STANDARD CHARTERED BANK',
'STATE BANK OF BIKANER AND JAIPUR',
'STATE BANK OF HYDERABAD',
'STATE BANK OF INDIA',
'STATE BANK OF MAURITIUS LTD',
'STATE BANK OF MYSORE',
'STATE BANK OF PATIALA',
'STATE BANK OF TRAVANCORE',
'SUMITOMO MITSUI BANKING CORPORATION',
'SYNDICATE BANK',
'TAMILNAD MERCANTILE BANK LTD',
'THANE BHARAT SAHAKARI BANK LTD',
'THE A.P. MAHESH CO-OP URBAN BANK LTD.',
'THE AHMEDABAD MERCANTILE CO-OPERATIVE BANK LTD.',
'THE ANDHRA PRADESH STATE COOP BANK LTD',
'THE BANK OF NOVA SCOTIA',
'THE BANK OF RAJASTHAN LTD',
'THE BHARAT CO-OPERATIVE BANK (MUMBAI) LTD',
'THE COSMOS CO-OPERATIVE BANK LTD.',
'THE DELHI STATE COOPERATIVE BANK LTD.',
'THE FEDERAL BANK LTD',
'THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LTD',
'THE GREATER BOMBAY CO-OP. BANK LTD',
'THE GUJARAT STATE CO-OPERATIVE BANK LTD',
'THE JALGAON PEOPLES CO-OP BANK',
'THE JAMMU AND KASHMIR BANK LTD',
'THE KALUPUR COMMERCIAL CO. OP. BANK LTD.',
'THE KALYAN JANATA SAHAKARI BANK LTD.',
'THE KANGRA CENTRAL CO-OPERATIVE BANK LTD',
'THE KANGRA COOPERATIVE BANK LTD',
'THE KARAD URBAN CO-OP BANK LTD',
'THE KARNATAKA STATE APEX COOP. BANK LTD.',
'THE LAKSHMI VILAS BANK LTD',
'THE MEHSANA URBAN COOPERATIVE BANK LTD',
'THE MUNICIPAL CO OPERATIVE BANK LTD MUMBAI',
'THE NAINITAL BANK LIMITED',
'THE NASIK MERCHANTS CO-OP BANK LTD. NASHIK',
'THE RAJASTHAN STATE COOPERATIVE BANK LTD.',
'THE RATNAKAR BANK LTD',
'THE ROYAL BANK OF SCOTLAND N.V',
'THE SAHEBRAO DESHMUKH CO-OP. BANK LTD.',
'THE SARASWAT CO-OPERATIVE BANK LTD',
'THE SEVA VIKAS CO-OPERATIVE BANK LTD (SVB)',
'THE SHAMRAO VITHAL CO-OPERATIVE BANK LTD',
'THE SURAT DISTRICT CO OPERATIVE BANK LTD.',
'THE SURAT PEOPLES CO-OP BANK LTD',
'THE SUTEX CO.OP. BANK LTD.',
'THE TAMILNADU STATE APEX COOPERATIVE BANK LIMITED',
'THE THANE DISTRICT CENTRAL CO-OP BANK LTD',
'THE THANE JANATA SAHAKARI BANK LTD',
'THE VARACHHA CO-OP. BANK LTD.',
'THE VISHWESHWAR SAHAKARI BANK LTD. PUNE',
'THE WEST BENGAL STATE COOPERATIVE BANK LTD',
'TJSB SAHAKARI BANK LTD.',
'TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LTD.',
'UBS AG',
'UCO BANK',
'UNION BANK OF INDIA',
'UNITED BANK OF INDIA',
'UNITED OVERSEAS BANK',
'VASAI VIKAS SAHAKARI BANK LTD.',
'VIJAYA BANK',
'WEST BENGAL STATE COOPERATIVE BANK',
'WESTPAC BANKING CORPORATION',
'WOORI BANK',
'YES BANK LTD',
'ZILA SAHKARI BANK LTD GHAZIABAD',
],
'Kenya': [
    'UBA Kenya Bank Ltd',
    'The Co-operative Bank',
    'Suntra Investment Bank Ltd',
    'Sterling Investment Bank',
    'Standard Investment Bank',
    'Prime Bank',
    'Paramount Bank',
    'Oriental Commercial Bank Ltd.',
    'NIC Bank',
    'ABC Bank',
    'National Bank',
    'K-Rep Bank',
    'Kenya Post Office Savings Bank',
    'KCB Bank',
    'Investments & Mortgages Bank Limited – I&M Bank',
    'Imperial Bank Limited',
    'Housing Finance',
    'Guardian Bank Ltd.',
    'Giro Commercial Bank Ltd',
    'Fina Bank',
    'Fidelity Bank',
    'Faida Investment Bank – FIB',
    'Equity Bank',
    'Equatorial Investment Bank',
    'Equatorial Commercial Bank Limited',
    'Dyer & Blair Investment Bank',
    'Dubai Bank Kenya Ltd',
    'Dry Associates Limited',
    'Development Bank Of Kenya Ltd',
    'Co-operative Bank',
    'Consolidated Bank',
    'Commercial Bank of Africa',
    'Citibank N A',
    'Chase Bank',
    'CFC Stanbic Bank Limited',
    'Central Bank of Kenya',
    'Bank Of Baroda (Kenya) Ltd.',
    'Bank of Africa Kenya Ltd',
    'Afrika Investment Bank',
    'African Development Bank Group',
    'African Banking Corporation',
    ],
    'Unitedkingdom' : [ 
        "United Overseas Bank" ,
        'Lloyds Banking Group',
        'NatWest',
        'Santander UK',
        'CYBG PLC	',
        'Virgin Money Holdings (UK)	',
        'The Co-operative Bank	',
        'Metro Bank',
        'Tesco Bank',
           'Abbey National Treasury Services plc',
           'ABC International Bank plc',
           'Access Bank UK Limited',
           'Ahli United Bank (UK) plc',
           'Airdrie Savings Bank',
           'Allied Bank',
           'Alpha Bank',
           'AMC Bank Ltd',
           'Anglo-Romanian Bank Ltd',
           'ANZ Bank (Europe) Ltd',
           'Banc of America Securities Ltd',
           'Bank Leumi (UK) plc',
           'Bank Mandiri (Europe) Ltd',
           'Bank of Beirut (UK) Ltd',
           'Bank of China (UK) Limited',
           'Bank of London and The Middle East plc',
           'Bank of New York Mellon (International) Limited',
           'Bank of Philippine Islands (Europe), PLC',
           'Bank of Scotland plc',
           'Bank Saderat plc',
           'Bank Sepah International plc',
           'Barclays Bank plc',
           'Bradford & Bingley plc',
           'British Arab Commercial Bank Ltd',
           'Broadcastle Bank ltd',
           'Brown Shipley & Co. Ltd',
           'Butterfield Bank (UK) Ltd',
           'C Hoare & Co Investec Bank (UK) Ltd',
           'CAF Bank Ltd',
           'Capital One Bank (Europe) plc',
           'Cater Allen Ltd',
           'Charity Bank Ltd',
           'Church House Trust plc',
           'CIBC World Markets plc',
           'Citi Financial Europe plc',
           'Citibank International plc',
           'Close Brothers Ltd',
           'Clydesdale Bank plc',
           'Consolidated Credits Bank Ltd',
           'Conversbank (UK) Limited',
           'Co-operative Bank plc, The',
           'Coutts & Co',
           'Credit Suisse International',
           'Crown Agents Bank Ltd',
           'DB UK Bank Limited',
           'Dresdner Kleinwort Limited',
           'Dunbar Bank plc',
           'EFG Private Bank Ltd',
           'Egg Bank plc',
           'Europe Arab Bank Plc',
           'European Finance House Ltd',
           'European Islamic Investment Bank Plc',
           'FBN Bank (UK) Ltd',
           'FCE Bank plc',
           'FIBI Bank (UK) plc',
           'First Trust Bank',
           'Gatehouse Bank plc',
           'GE Capital Bank Ltd',
           'Ghana International Bank plc',
           'Goldman Sachs International Bank',
           'Gulf International Bank (UK) Ltd',
           'Habib Allied International Bank plc',
           'Harrods Bank Ltd',
           'Havin Bank Ltd',
           'HBOS Bank',
           'Heritable Bank Ltd',
           'HFC Bank plc',
           'HSBC Bank plc',
           'ICBC',
           'ICICI Bank',
           'Intercontinental Bank (UK) plc',
           'Islamic Bank of Britain plc',
           'Ivobank Limited',
           'J P Morgan International Bank Ltd',
           'Jordan International Bank plc',
           'Julian Hodge Bank Ltd',
           'Kaupthing Singer & Friedlander Limited',
           'Kexim Bank (UK) Ltd',
           'Kingdom Bank Ltd',
           'Kleinwort Benson Private Bank',
           'Kookmin Bank International Ltd',
           'Liverpool Victoria Banking Services Ltd',
           'Lloyds TSB Bank plc',
           'London Scottish Bank plc',
           'Macquarie Bank International Limited',
           'MBNA Europe Bank Ltd',
           'MediCapital Bank plc',
           'Melli Bank plc',
           'Methodist Chapel Aid Ltd',
           'Mizuho International plc',
           'Morgan Stanley Bank International Ltd',
           'N M Rothschild & Sons Ltd',
           'National Bank of Egypt International Ltd',
           'National Bank of Kuwait (International) plc',
           'National Westminster Bank plc',
           'Nomura Bank International plc',
           'Northern Bank Ltd',
           'Northern Rock plc',
           'Northern Trust Global Services Limited',
           'Persia International Bank Ltd',
           'Philippine National Bank (Europe) plc',
           'R Raphael & Sons plc',
           'Rathbone Investment Management Ltd',
           'Reliance Bank Ltd',
           'Royal Bank of Canada Europe Ltd',
           'Royal Bank of Scotland plc',
           'Ruffler Bank plc',
           'Sainsbury’s Bank plc',
           'Schroder & Co Ltd',
           'Scotiabank Europe plc',
           'Scottish Widows Bank plc',
           'Secure Trust Bank plc',
           'SG Hambros Bank Limited',
           'Smith & Williamson Investment Management Ltd',
           'Sonali Bank (UK) Ltd',
           'Southsea Mortgage & Investment Co Ltd',
           'Standard Bank Plc',
           'Standard Chartered Bank',
           'Standard Life Bank Ltd',
           'State Street Bank Europe Ltd',
           'Sumitomo Mitsui Banking Corporation Europe Ltd',
           'TD Bank Europe Ltd',
           'The Hampshire Trust plc',
           'Turkish Bank (UK) Ltd',
           'UBS Bank',
           'Ulster Bank Ltd',
           'Union Bank UK plc',
           'United National Bank Ltd',
           'United Trust Bank Ltd',
           'Vanquis Bank Ltd',
           'VTB Bank Europe Plc',
           'Weatherbys Bank Ltd',
           'Wesleyan Bank Limited',
           'West Merchant Bank Ltd',
           'Westpac Europe Limited',
           'Whiteaway Laidlaw Bank Ltd',
           'Zenith Bank (UK) Limited'
       ],
    'UnitedKingdom' : [ 
	 "United Overseas Bank" ,
     'Lloyds Banking Group',
     'NatWest	',
     'Santander UK',
     'CYBG PLC	',
     'Virgin Money Holdings (UK)	',
     'The Co-operative Bank	',
     'Metro Bank',
     'Tesco Bank',
        'Abbey National Treasury Services plc',
        'ABC International Bank plc',
        'Access Bank UK Limited',
        'Ahli United Bank (UK) plc',
        'Airdrie Savings Bank',
        'Allied Bank',
        'Alpha Bank',
        'AMC Bank Ltd',
        'Anglo-Romanian Bank Ltd',
        'ANZ Bank (Europe) Ltd',
        'Banc of America Securities Ltd',
        'Bank Leumi (UK) plc',
        'Bank Mandiri (Europe) Ltd',
        'Bank of Beirut (UK) Ltd',
        'Bank of China (UK) Limited',
        'Bank of London and The Middle East plc',
        'Bank of New York Mellon (International) Limited',
        'Bank of Philippine Islands (Europe), PLC',
        'Bank of Scotland plc',
        'Bank Saderat plc',
        'Bank Sepah International plc',
        'Barclays Bank plc',
        'Bradford & Bingley plc',
        'British Arab Commercial Bank Ltd',
        'Broadcastle Bank ltd',
        'Brown Shipley & Co. Ltd',
        'Butterfield Bank (UK) Ltd',
        'C Hoare & Co Investec Bank (UK) Ltd',
        'CAF Bank Ltd',
        'Capital One Bank (Europe) plc',
        'Cater Allen Ltd',
        'Charity Bank Ltd',
        'Church House Trust plc',
        'CIBC World Markets plc',
        'Citi Financial Europe plc',
        'Citibank International plc',
        'Close Brothers Ltd',
        'Clydesdale Bank plc',
        'Consolidated Credits Bank Ltd',
        'Conversbank (UK) Limited',
        'Co-operative Bank plc, The',
        'Coutts & Co',
        'Credit Suisse International',
        'Crown Agents Bank Ltd',
        'DB UK Bank Limited',
        'Dresdner Kleinwort Limited',
        'Dunbar Bank plc',
        'EFG Private Bank Ltd',
        'Egg Bank plc',
        'Europe Arab Bank Plc',
        'European Finance House Ltd',
        'European Islamic Investment Bank Plc',
        'FBN Bank (UK) Ltd',
        'FCE Bank plc',
        'FIBI Bank (UK) plc',
        'First Trust Bank',
        'Gatehouse Bank plc',
        'GE Capital Bank Ltd',
        'Ghana International Bank plc',
        'Goldman Sachs International Bank',
        'Gulf International Bank (UK) Ltd',
        'Habib Allied International Bank plc',
        'Harrods Bank Ltd',
        'Havin Bank Ltd',
        'HBOS Bank',
        'Heritable Bank Ltd',
        'HFC Bank plc',
        'HSBC Bank plc',
        'ICBC',
        'ICICI Bank',
        'Intercontinental Bank (UK) plc',
        'Islamic Bank of Britain plc',
        'Ivobank Limited',
        'J P Morgan International Bank Ltd',
        'Jordan International Bank plc',
        'Julian Hodge Bank Ltd',
        'Kaupthing Singer & Friedlander Limited',
        'Kexim Bank (UK) Ltd',
        'Kingdom Bank Ltd',
        'Kleinwort Benson Private Bank',
        'Kookmin Bank International Ltd',
        'Liverpool Victoria Banking Services Ltd',
        'Lloyds TSB Bank plc',
        'London Scottish Bank plc',
        'Macquarie Bank International Limited',
        'MBNA Europe Bank Ltd',
        'MediCapital Bank plc',
        'Melli Bank plc',
        'Methodist Chapel Aid Ltd',
        'Mizuho International plc',
        'Morgan Stanley Bank International Ltd',
        'N M Rothschild & Sons Ltd',
        'National Bank of Egypt International Ltd',
        'National Bank of Kuwait (International) plc',
        'National Westminster Bank plc',
        'Nomura Bank International plc',
        'Northern Bank Ltd',
        'Northern Rock plc',
        'Northern Trust Global Services Limited',
        'Persia International Bank Ltd',
        'Philippine National Bank (Europe) plc',
        'R Raphael & Sons plc',
        'Rathbone Investment Management Ltd',
        'Reliance Bank Ltd',
        'Royal Bank of Canada Europe Ltd',
        'Royal Bank of Scotland plc',
        'Ruffler Bank plc',
        'Sainsbury’s Bank plc',
        'Schroder & Co Ltd',
        'Scotiabank Europe plc',
        'Scottish Widows Bank plc',
        'Secure Trust Bank plc',
        'SG Hambros Bank Limited',
        'Smith & Williamson Investment Management Ltd',
        'Sonali Bank (UK) Ltd',
        'Southsea Mortgage & Investment Co Ltd',
        'Standard Bank Plc',
        'Standard Chartered Bank',
        'Standard Life Bank Ltd',
        'State Street Bank Europe Ltd',
        'Sumitomo Mitsui Banking Corporation Europe Ltd',
        'TD Bank Europe Ltd',
        'The Hampshire Trust plc',
        'Turkish Bank (UK) Ltd',
        'UBS Bank',
        'Ulster Bank Ltd',
        'Union Bank UK plc',
        'United National Bank Ltd',
        'United Trust Bank Ltd',
        'Vanquis Bank Ltd',
        'VTB Bank Europe Plc',
        'Weatherbys Bank Ltd',
        'Wesleyan Bank Limited',
        'West Merchant Bank Ltd',
        'Westpac Europe Limited',
        'Whiteaway Laidlaw Bank Ltd',
        'Zenith Bank (UK) Limited'
    ],
    'malaysia': [
        "Maybank" ,
        "CIMB Bank" ,
        "RHB Bank" ,
        "Bank Islam" ,
        "Bank Muamalat" ,
        "Bank Rakyat" ,
        "Bank Simpanan Nasional" ,
        "Citibank" ,
        "Hong Leong Bank" ,
        "HSBC Bank" ,
        "OCBC Bank" ,
        "Public Bank" ,
        "Affin Bank" ,
        "AmBank" ,
        "Agro Bank" ,
        "Alliance Bank" ,
        "Al-Rajhi Bank" ,
        "Bank of China" ,
        "Bank of America" ,
        "Bank of Tokyo-Mitsubishi UFJ" ,
        "BNP Paribas" ,
        "Deutsche Bank" ,
        "Industrial & Commercial Bank of China" ,
        "JP Morgan Chase Bank" ,
        "Kuwait Finance House" ,
        "Mizuho Bank" ,
    ],

    
    'SouthAfrca': [
        'Absa Bank Ltd',
    'African Bank Ltd',
    'Albaraka Bank Limited',
    'BoE Private Clients',
    'Bidvest Bank Limited',
    'Capitec Bank Ltd',
    'FirstRand Bank Ltd',
    'Grindrod Bank',
    'Habib Overseas Bank Limited',
    'HBZ Bank Limited',
    'Investec Bank Ltd',
    'Mercantile Bank Limited',
    'Nedbank Group Limited',
    'Rand Merchant Bank',
    'RMB Private Bank ',
    'South African Bank of Athens Limited',
    'Sasfin Bank Ltd',
    'Standard Bank of SA Ltd',
    'Wesbank',
    ],
    '':[
        
    ]

 }

 


